<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.citeck.ecos.events</groupId>
    <artifactId>ecos-events2-project</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>ru.citeck.lib.commons</groupId>
        <artifactId>citeck-lib-base-parent</artifactId>
        <version>1.2.0</version>
    </parent>

    <properties>

        <revision>2.21.2</revision>

        <ecos.commons.version>3.8.4</ecos.commons.version>
        <ecos.records.version>3.76.12</ecos.records.version>
        <ecos.model-lib.version>2.39.0</ecos.model-lib.version>
        <ecos.txn-lib.version>1.4.4</ecos.txn-lib.version>

        <ecos.zookeeper.version>1.10.2</ecos.zookeeper.version>
        <ecos.rabbitmq.version>2.11.0</ecos.rabbitmq.version>

        <ecos-test-commons.version>1.13.0</ecos-test-commons.version>

    </properties>

    <dependencies>

        <dependency>
            <groupId>ru.citeck.ecos.records</groupId>
            <artifactId>ecos-records</artifactId>
            <version>${ecos.records.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ru.citeck.ecos.model</groupId>
            <artifactId>ecos-model-lib</artifactId>
            <version>${ecos.model-lib.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ru.citeck.ecos.commons</groupId>
            <artifactId>ecos-commons</artifactId>
            <version>${ecos.commons.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ru.citeck.ecos.commons</groupId>
            <artifactId>ecos-commons-deps</artifactId>
            <version>${ecos.commons.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ru.citeck.ecos.txn</groupId>
            <artifactId>ecos-txn-lib</artifactId>
            <version>${ecos.txn-lib.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ru.citeck.ecos.test.commons</groupId>
            <artifactId>ecos-test-commons</artifactId>
            <version>${ecos-test-commons.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>

        </plugins>

    </build>

    <modules>
        <module>ecos-events2</module>
        <module>ecos-events2-rabbitmq</module>
    </modules>

    <distributionManagement>
        <repository>
            <id>citeck-community-releases</id>
            <url>${community.releases.distr.url}</url>
        </repository>
        <snapshotRepository>
            <id>citeck-community-snapshots</id>
            <url>${community.snapshots.distr.url}</url>
        </snapshotRepository>
    </distributionManagement>

</project>
